spring.datasource.url=jdbc:mysql://localhost:3306/videojuegos?serverTimezone=GMT-3
spring.datasource.username=videojuegos
spring.datasource.password=videojuegos

# Stripe Configuration
stripe.api.key.public=pk_test_your_public_key
stripe.api.key.secret=sk_test_your_secret_key
stripe.api.key.webhook=whsec_your_webhook_secret
stripe.currency=usd
